<?php
class FilecacheTest extends PHPUnit_Framework_TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        \Aw\Filesystem\Filesystem::createDir(__DIR__."/cache");
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        \Aw\Filesystem\Filesystem::delDir(__DIR__."/cache");
    }

    public function testFile()
    {

    	$cache = new Aw\Cache\FileCache(__DIR__."/cache");
    	$cache->set('key', 'taw');
    	$this->assertEquals($cache->get('key'), 'taw');
    	$cache->set('balabala', 'balabala',1);
    	$this->assertEquals($cache->get('balabala'), 'balabala');
    	sleep(2);
    	//     	print $cache->get('balabala');
    	$this->assertEquals($cache->get('balabala'), null);
    	$cache->flush();
    }
    public function testFileArr()
    {

        $cache = new Aw\Cache\FileCache(__DIR__."/cache");
    	$data = array(
    			'k1' => '123',
    			'ba' => 'balabala',
    			'arr' => array(2,54)
        );
    	$cache->set('key', $data);
    	//var_dump($cache->get('key'));
        $cache->flush();
    }
    public function testNonexist()
    {
        $cache = new Aw\Cache\FileCache(__DIR__."/cache");
    	$cache->set('false', false);
    	$this->assertNotTrue($cache->get('false'));
    	$this->assertNotTrue($cache->get('gogo'));
        $cache->flush();
    }
}


